version: '3'

# Глобальные переменные проекта
vars:
  GO_VERSION: '1.25.3'
  GOLANGCI_LINT_VERSION: 'v2.10.1'
  BUF_VERSION: '1.66.0'
  PROTOC_GEN_GO_VERSION: 'v1.36.11'
  PROTOC_GEN_GO_GRPC_VERSION: 'v1.6.1'
  SQLC_VERSION: 'v1.30.0'
  GOOSE_VERSION: 'v3.27.0'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  BUF: '{{.BIN_DIR}}/buf'
  PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-gen-go'
  PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-gen-go-grpc'
  SQLC: '{{.BIN_DIR}}/sqlc'
  GOOSE: '{{.BIN_DIR}}/goose'
  GOOSE_DIR: "services/user/internal/adapters/postgres/migrations"

  SERVICES: core,user
  GRPC_SERVER_ADDR: 'localhost:50051'

tasks:

  install-golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    cmds:
      - '[ -f {{.GOLANGCI_LINT}} ] || curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b {{.BIN_DIR}} {{.GOLANGCI_LINT_VERSION}}'
    status:
      - test -x {{.GOLANGCI_LINT}}

  format:
    desc: "Форматирует весь проект через golangci-lint (gofumpt + gci)"
    deps: [ install-golangci-lint ]
    cmds:
      - echo "🧼 Форматируем проект..."
      - "{{.GOLANGCI_LINT}} fmt"

  lint:
    desc: "Lint the whole workspace or specific path"
    deps: [ install-golangci-lint ]
    cmds:
      - echo "🔍 Линтим весь workspace..."
      # ./... в корне с go.work автоматически подхватит все модули
      # To lint one service: task lint -- services/user/...
      - "{{.GOLANGCI_LINT}} run {{.CLI_ARGS | default \"./...\"}}"

  lint:fast:
    desc: "Линтит только измененные файлы"
    cmds:
      - "{{.GOLANGCI_LINT}} run --new-from-rev=HEAD~1"

  lint:fix:
    desc: "Fix lint errors and format code"
    cmds:
      - "{{.GOLANGCI_LINT}} fmt {{.CLI_ARGS}}"
      - "{{.GOLANGCI_LINT}} run --fix {{.CLI_ARGS | default \"./...\"}}"

  lint:check:
    desc: "Verify .golangci.yml is valid"
    cmds:
      - "{{.GOLANGCI_LINT}} config verify"


  install-buf:
    desc: "Install Buf CLI"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - '[ -f {{.BUF}} ] || GOBIN={{.BIN_DIR}} go install github.com/bufbuild/buf/cmd/buf@v{{.BUF_VERSION}}'
    status:
      - test -x {{.BUF}}


  proto:gen:
      desc: "Generate Go code and OpenAPI specs from .proto"
      deps: [ install-buf ]
      dir: "{{.ROOT_DIR}}/proto"
      cmds:
        - echo "🔍 Linting..."
        - "{{.BUF}} lint"
        - echo "🛠 Generating..."
        - "{{.BUF}} dep update"   # синхронизировать buf.lock
        - "{{.BUF}} generate"
        - echo "✅ Done. Check shared/gen/go/ and api/"

  proto:update:
    desc: "Update buf.lock (run after changing deps in buf.yaml)"
    dir: "{{.ROOT_DIR}}/proto"
    cmds:
      - "{{.BUF}} dep update"

  proto:breaking:
    desc: "Check for breaking changes against main"
    deps: [install-buf]
    dir: "{{.ROOT_DIR}}/proto"
    cmds:
      - "{{.BUF}} breaking --against '../.git#branch=main,subdir=proto'"

  proto:lint:
    deps: [install-buf]
    dir: "{{.ROOT_DIR}}/proto"
    cmds:
      - "{{.BUF}} lint"


  install-sqlc:
    desc: "Install sqlc CLI"
    cmds:
      - '[ -f {{.SQLC}} ] || GOBIN={{.BIN_DIR}} go install github.com/sqlc-dev/sqlc/cmd/sqlc@{{.SQLC_VERSION}}'
    status:
      - test -x {{.SQLC}}

  sqlc:gen:
    desc: "Generate Go code from SQL"
    dir: "{{.ROOT_DIR}}/services/user/internal/adapters/postgres"
    cmds:
      - "{{.SQLC}} generate"


  install:goose:
    cmds:
      - '[ -f {{.GOOSE}} ] || GOBIN={{.BIN_DIR}} go install github.com/pressly/goose/v3/cmd/goose@{{.GOOSE_VERSION}}'
    status:
      - test -x {{.GOOSE}}

  goose:rollback:
    desc: "Rollback last migration (emergency use)"
    deps: [install:goose]
    cmds:
      - "{{.GOOSE}} -dir {{.GOOSE_DIR}} postgres '{{.DATABASE_URL}}' down"

  # task goose:status DATABASE_URL="postgres://user:pass@localhost:5432/userdb"
  goose:status:
    desc: "Show applied/pending migrations"
    deps: [install:goose]
    cmds:
      - "{{.GOOSE}} -dir {{.GOOSE_DIR}} postgres '{{.DATABASE_URL}}' status"

  # task goose:create NAME=add_users_table
  goose:create:
    desc: "Create new migration file"
    deps: [install:goose]
    cmds:
      - "{{.GOOSE}} -dir {{.GOOSE_DIR}} create {{.NAME}} sql"



  run:user:
    desc: "Run user service (memory repo, no DB needed)"
    dir: "{{.ROOT_DIR}}/services/user"
    env:
      SERVICE_NAME: "user"
      ENV: "dev"
      GRPC_PORT: "50051"
      HTTP_PORT: "8080"
      OTEL_ENABLED: "false"
      # DATABASE_URL не задан → memory repo
    cmds:
      - go run ./cmd/api/

  run:user:postgres:
    desc: "Run user service with PostgreSQL"
    dir: "{{.ROOT_DIR}}/services/user"
    env:
      SERVICE_NAME: "user"
      ENV: "dev"
      GRPC_PORT: "50051"
      HTTP_PORT: "8080"
      OTEL_ENABLED: "false"
      DATABASE_URL: "postgres://user:password@localhost:5432/userdb?sslmode=disable"
    cmds:
      - go run ./cmd/api/