// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	//CountUsers
	//
	//  SELECT COUNT(*) FROM users
	CountUsers(ctx context.Context) (int64, error)
	//DeleteUser
	//
	//  DELETE FROM users
	//  WHERE id = $1
	DeleteUser(ctx context.Context, id uuid.UUID) error
	//GetUserByEmail
	//
	//  SELECT id, email, first_name, last_name, created_at, updated_at FROM users
	//  WHERE email = $1
	GetUserByEmail(ctx context.Context, email string) (User, error)
	//GetUserByID
	//
	//  SELECT id, email, first_name, last_name, created_at, updated_at FROM users
	//  WHERE id = $1
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	//InsertUser
	//
	//  INSERT INTO users (id, email, first_name, last_name, created_at, updated_at)
	//  VALUES ($1, $2, $3, $4, $5, $6)
	//  RETURNING id, email, first_name, last_name, created_at, updated_at
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	//ListUsers
	//
	//  SELECT id, email, first_name, last_name, created_at, updated_at FROM users
	//  ORDER BY created_at DESC
	//  LIMIT $1 OFFSET $2
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	//UpdateUser
	//
	//  UPDATE users
	//  SET
	//      first_name = COALESCE($2, first_name),
	//      last_name  = COALESCE($3, last_name),
	//      email      = COALESCE($4, email),
	//      updated_at = NOW()
	//  WHERE id = $1
	//  RETURNING id, email, first_name, last_name, created_at, updated_at
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
